# Generated by Django 4.2.3 on 2023-07-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('IDLE', 'Idle')], default='IDLE', max_length=5)),
                ('is_operational', models.BooleanField(default=True)),
                ('current_floor', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('elevator', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='elevator_system.elevator')),
            ],
        ),
    ]
