# Generated by Django 4.2.3 on 2023-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0002_alter_elevator_current_floor_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
