# Generated by Django 4.2.3 on 2023-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0003_alter_elevator_current_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='requests',
            field=models.ManyToManyField(related_name='elevators', to='elevator_system.request'),
        ),
    ]
