# Generated by Django 4.2.3 on 2023-07-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0004_elevator_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='elevator',
        ),
    ]
