# Generated by Django 4.2.3 on 2023-07-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0005_remove_request_elevator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='requests',
        ),
        migrations.AddField(
            model_name='request',
            name='elevator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='elevator_system.elevator'),
        ),
    ]
