# Generated by Django 4.2.3 on 2023-07-16 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0009_alter_elevator_id_alter_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
