# Generated by Django 4.2.3 on 2023-07-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0010_alter_elevator_id_alter_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='id',
            field=models.CharField(default='eece6ed04dbf49cdb3891f3b80b9eaa4', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.CharField(default='eb066fdeeb554d129dad43b8ee5ceaed', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
