# Generated by Django 4.2.3 on 2023-07-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0011_alter_elevator_id_alter_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='id',
            field=models.CharField(default='181885f7233448579e1f82a047469085', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.CharField(default='f9f4f238a1d743289755a8da554ac408', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
