# Generated by Django 4.2.3 on 2023-07-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0013_alter_elevator_id_alter_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
