# Generated by Django 4.2.3 on 2023-07-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0014_elevator_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='current_direction',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('IDLE', 'Idle')], default='IDLE', max_length=5),
        ),
    ]
